kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Chart.Name }}-{{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Chart.Name }}-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Release.Name }}
          image: {{ .Values.image.url }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-{{ .Release.Name }}-credentials
